List<String> Question(){
  return [
    "What Is The Capital Of Palestine?",
    "In which continent is Palestine located?",
    "What is the area of Palestine? ",
    "What is the population of Palestine? ",
    "A famous desert located in the south of Palestine, what is it?",
    "What are the borders of Palestine from the east?",
    "What are the borders of Palestine from the west?",
    "What are the borders of Palestine from the north?",
    "What are the borders of Palestine from the south?",
    "What is the largest country by area in Africa?",
    "Who is the European city called the city of fog?",
    "What country watched TV for the first time?",
    "Where was the first place where gunpowder was invented?",
    "What does the name Los Angeles mean?",
    "What is the intended day, the Day of Criterion, which was mentioned in the Book of God Almighty?",
    "What is the land of the cradle of the monotheistic religions that God Almighty swore?",
    "What is the first foray of Muslims?",
    "Where was the first covering of the Kaaba made?",
    "How many gates of heaven?",
    "What is the chemical name for chalk?",
    "Who is the scientist who discovered the micro-circulation?",
    "Who invented the electric light bulb?",
    "How many bones in the human body?",
    "How many muscles does the body use when a person speaks?",
    "How many heart valves in the human body?",
    "What is the gas present in a large proportion in the human body?",
  ];
}