List<List<String>> answer(){
  return [
    ["Ramallah","Gaza","Quds","Hebron"],
    ["Africa","Asia","Europa","South America"],
    ["7320 KM","8970 KM","6220 KM","4390 KM"],
    ["7 Million","5 Million","3 Million","10 Million"],
    ["Tataouine desert","white desert","Al-Dahna desert","Negev desert"],
    ["Tunisia","Syria","Jordan","Egypt"],
    ["Syria","Egypt","The Mediterranean Sea","The Red Sea"],
    ["Lebanon and Syria","Lebanon and Qatar","Egypt","Syria"],
    ["Syria","Egypt and the Gulf of Aqaba","Lebanon","Qatar"],
    ["Sudan","Egypt","Mauritania","Tunisia"],
    ["Paris","London","New York","Madrid"],
    ["America","Egypt","Europa","China"],
    ["Roman","Arab","China","America"],
    ["City of Angels","City of Treasures","City of Gardens","no correct answer"],
    ["The conquest of Mecca","Battle of Tabuk","Battle of Badr","no correct answer"],
    ["Hejaz","Egypt","Palestine","no correct answer"],
    ["The Battle of Tabuk","The Battle of Mu'tah","The Battle of Wadan","no correct answer"],
    ["Saudi Arabia","Egypt","Palestine","no correct answer"],
    ["Ten gates","seven gates","eight gates","no correct answer"],
    ["Calcium carbonate","chlorate","sulphide","no correct answer"],
    ["Hassan Al Basri","Ibn al-Nafis","Ibn Khaldun","no correct answer"],
    ["Thomas Lemar","Thomas Friedman","Thomas Alva Edison","no correct answer"],
    ["206","207","208","209"],
    ["43","44","45","46"],
    ["4","6","8","10"],
    ["oxygen gas","hydrogen gas","carbon dioxide gas","Nitrogen gas"],
  ];
}