List<String> final_answers(){
  return [
    "Quds",
    "Asia",
    "6220 KM",
    "5 Million",
    "Negev desert",
    "Jordan",
    "The Mediterranean Sea",
    "Lebanon and Syria",
    "Egypt and the Gulf of Aqaba",
    "Sudan",
    "London",
    "America",
    "China",
    "City of Angels",
    "Battle of Badr",
    "Palestine",
    "The Battle of Wadan",
    "Egypt",
    "eight gates",
    "Calcium carbonate",
    "Ibn al-Nafis",
    "Thomas Alva Edison",
    "206",
    "43",
    "4",
    "oxygen gas",
  ];
}